version: "3.7"
networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
services:
  web:
    restart: always
    container_name: web
    image: kolenich/web
    ports:
      - 80:80
    networks:
      - frontend
  server:
    restart: always
    container_name: server
    image: kolenich/server
    networks:
      - frontend
      - backend
  postgres:
    restart: always
    container_name: postgres
    image: kolenich/postgres
    networks:
      - backend

