version: "3.7"

networks:
  web-server:
    name: web-server
    driver: bridge
  server-postgres:
    name: server-postgres
    driver: bridge
  server-rabbitmq:
    name: server-rabbitmq
    driver: bridge

volumes:
  static:
    name: static
  postgres_data:
    name: postgres_data
    driver_opts:
      type: none
      o: bind
      device: $PWD/postgres_data

services:
  web:
    volumes:
      - static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    container_name: web
    image: kolenich/web
    ports:
      - 80:80
      - 443:443
    networks:
      - web-server
    depends_on:
      - server

  server:
    volumes:
      - static:/app/static
      - ./media:/app/media
      - ./settings.yml:/app/settings.yml
    restart: always
    container_name: server
    image: kolenich/server
    environment:
      - PROJECT_MODE=production
    networks:
      - web-server
      - server-postgres
      - server-rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    restart: always
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nikolay
      - POSTGRES_PASSWORD=Crowel_16
    networks:
      - server-postgres

  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=kolenich
      - RABBITMQ_DEFAULT_PASS=Crowel_16
      - RABBITMQ_DEFAULT_VHOST=kolenich-host
    networks:
      - server-rabbitmq
