version: "3.7"

networks:
  default:
    name: diary-network
  proxy:
    external:
      name: proxy

volumes:
  static:
    name: diary-static
  postgres-data:
    name: diary-postgres-data
    driver_opts:
      type: none
      o: bind
      device: $PWD/postgres-data

services:
  diary-web:
    volumes:
      - static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    restart: always
    container_name: diary-web
    image: kolenich/diary:web
    networks:
      - proxy
      - default
    depends_on:
      - diary-server

  diary-server:
    volumes:
      - static:/app/static
      - ./media:/app/media
    restart: always
    container_name: diary-server
    image: kolenich/diary:server
    environment:
      - PROJECT_MODE=production
      - REDIS_HOST=diary-redis
    depends_on:
      - diary-postgres
      - diary-rabbitmq
      - diary-redis

  diary-postgres:
    restart: always
    container_name: diary-postgres
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nikolay
      - POSTGRES_PASSWORD=Crowel_16

  diary-rabbitmq:
    restart: always
    container_name: diary-rabbitmq
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=kolenich
      - RABBITMQ_DEFAULT_PASS=Crowel_16
      - RABBITMQ_DEFAULT_VHOST=kolenich-host

  diary-redis:
    restart: always
    container_name: diary-redis
    image: redis:alpine
