version: "3.7"

networks:
  default:
    name: kolenich-network
  proxy:
    external:
      name: proxy

volumes:
  static:
    name: kolenich-static
  postgres_data:
    name: kolenich-postgres_data
    driver_opts:
      type: none
      o: bind
      device: $PWD/postgres_data

services:
  kolenich-web:
    volumes:
      - static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    container_name: kolenich-web
    image: kolenich/web
    networks:
      - proxy
      - default
    depends_on:
      - kolenich-server

  kolenich-server:
    volumes:
      - static:/app/static
      - ./media:/app/media
      - ./settings.yml:/app/settings.yml
    restart: always
    container_name: kolenich-server
    image: kolenich/server
    environment:
      - PROJECT_MODE=production
    depends_on:
      - kolenich-postgres
      - kolenich-rabbitmq

  kolenich-postgres:
    restart: always
    container_name: kolenich-postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nikolay
      - POSTGRES_PASSWORD=Crowel_16

  kolenich-rabbitmq:
    restart: always
    container_name: kolenich-rabbitmq
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=kolenich
      - RABBITMQ_DEFAULT_PASS=Crowel_16
      - RABBITMQ_DEFAULT_VHOST=kolenich-host
